[package]
name = "pipes"
version = "0.1.0"
authors = ["Owen Lynch <oclynch888@gmail.com>"]

[dependencies]
serde = "0.9"
serde_json = "0.9"
rmp-serde = "0.12"
serde_derive = "0.9"
argparse = "*"

[[bin]]
name = "pipes"

[[bin]]
name = "echoc"